{% set version = "0.16.0" %}

{% if cuda_compiler_version in (None, "None", True, False) %}
{% set cuda_major = 0 %}
{% else %}
{% set cuda_major = environ.get("cuda_compiler_version", "11.8").split(".")[0] | int %}
{% endif %}

package:
  name: kaolin
  version: {{ version }}

source:
  url: https://github.com/NVIDIAGameWorks/kaolin/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 08bc6b48a6e33a1628b66a87533ce0baf93d541fd8a0f2bbdb33489e193bca2a
  patches:
    - 0001-loosen-version-pins.patch

build:
  number: 0
  skip: true  # [cuda_compiler_version == "None"]
  skip: true  # [win]
requirements:
  build:
    - {{ compiler('cuda') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
  host:
    - python
    - pip
    # still using removed `from pkg_resources import packaging`
    - setuptools <70
    - cython
    - numpy
    - pytorch
    - pytorch =*=cuda*
    - cuda-version {{ cuda_compiler_version }}
    {% if cuda_major >= 12 %}
    - libcublas-dev
    - libcusolver-dev
    - libcusparse-dev
    {% endif %}
  run:
    - python
    - scipy
    - pillow
    - tqdm
    - pytorch =*=cuda*
    - pygltflib

test:
  imports:
    - kaolin

about:
  home: https://developer.nvidia.com/nvidia-kaolin
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: 'A Pytorch Library for Accelerating 3D Deep Learning Research '
  description: |
    NVIDIA Kaolin library provides a PyTorch API for working with a variety
    of 3D representations and includes a growing collection of
    GPU-optimized operations such as modular differentiable rendering,
    fast conversions between representations, data loading,
    3D checkpoints and more.
  dev_url: https://github.com/NVIDIAGameWorks/kaolin
  doc_url: https://kaolin.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - JennaLipscomb
    - mxr-conda
