{% set name = "kaolin" %}
{% set version = "0.15.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/NVIDIAGameWorks/kaolin/archive/refs/tags/v{{ version }}.tar.gz
  sha256: be1c02da148a79a5c02631d7eb30c080c079c7ea925fa89f7c4d2f24dbdfc03d
  patches:
    - 0001-loosen-version-pins.patch

build:
  number: 0
  skip: true  # [cuda_compiler_version == "None" or cuda_compiler_version == "10.2"]
  skip: true  # [win]
requirements:
  build:
    - {{ compiler('cuda') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
  host:
    - pip
    - python
    - cython
    - numpy
    - pytorch
    - pytorch =*=cuda*
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - pillow
    - tqdm
    - pytorch =*=cuda*

test:
  imports:
    - kaolin

about:
  home: https://developer.nvidia.com/nvidia-kaolin
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: 'A Pytorch Library for Accelerating 3D Deep Learning Research '
  description: |
    NVIDIA Kaolin library provides a PyTorch API for working with a variety
    of 3D representations and includes a growing collection of
    GPU-optimized operations such as modular differentiable rendering,
    fast conversions between representations, data loading,
    3D checkpoints and more.
  dev_url: https://github.com/NVIDIAGameWorks/kaolin
  doc_url: https://kaolin.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - JennaLipscomb
    - mxr-conda
