{% set version = "0.18.0" %}

package:
  name: kaolin
  version: {{ version }}

source:
  url: https://github.com/NVIDIAGameWorks/kaolin/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 264132280c4713c9554b7c13a8bcad2c0af4da51105cf6ce06dbf01011748aa0
  patches:
    - patches/0001-loosen-version-pins.patch

build:
  number: 2
  skip: true  # [cuda_compiler_version == "None"]
  skip: true  # [win]
requirements:
  build:
    - {{ compiler('cuda') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - sed  # [unix]
  host:
    - python
    - pip
    - setuptools
    - cython
    - numpy
    - pytorch
    - pytorch * cuda*
    - cuda-version {{ cuda_compiler_version }}
    - libcublas-dev
    - libcusolver-dev
    - libcusparse-dev
  run:
    - flask
    - ipycanvas
    - ipyevents
    - jupyter_client <8
    - openusd
    - pillow >=8.0.0
    - pygltflib
    - python
    - pytorch * cuda*
    - scipy
    - torchvision
    - tornado
    - tqdm >=4.51.0
    - warp-lang >=1.7

test:
  imports:
    - kaolin
  requires:
    - pip
    # Work around old jaxlib in the test env that requires flatbuffers <3
    # (only affects pip-check; kaolin does not depend on this)
    - python-flatbuffers <3.0a0
  commands:
    - pip check

about:
  home: https://developer.nvidia.com/nvidia-kaolin
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: 'A Pytorch Library for Accelerating 3D Deep Learning Research '
  description: |
    NVIDIA Kaolin library provides a PyTorch API for working with a variety
    of 3D representations and includes a growing collection of
    GPU-optimized operations such as modular differentiable rendering,
    fast conversions between representations, data loading,
    3D checkpoints and more.
  dev_url: https://github.com/NVIDIAGameWorks/kaolin
  doc_url: https://kaolin.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - JennaLipscomb
    - mxr-conda
    - h-vetinari
    - jeongseok-meta
