{% set version = "0.17.0" %}

{% if cuda_compiler_version in (None, "None", True, False) %}
{% set cuda_major = 0 %}
{% else %}
{% set cuda_major = environ.get("cuda_compiler_version", "11.8").split(".")[0] | int %}
{% endif %}

package:
  name: kaolin
  version: {{ version }}

source:
  url: https://github.com/NVIDIAGameWorks/kaolin/archive/refs/tags/v{{ version }}.tar.gz
  sha256: f7ec30abb1ab6c9e47701acbabc635111a274abfe50a1da16d5bdefdfe469ebb
  patches:
    - 0001-loosen-version-pins.patch

build:
  number: 0
  skip: true  # [cuda_compiler_version == "None"]
  skip: true  # [win]
requirements:
  build:
    - {{ compiler('cuda') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
  host:
    - python
    - pip
    - setuptools
    - cython
    - numpy
    - pytorch
    - pytorch =*=cuda*
    - cuda-version {{ cuda_compiler_version }}
    {% if cuda_major >= 12 %}
    - libcublas-dev
    - libcusolver-dev
    - libcusparse-dev
    {% endif %}
  run:
    - python
    - ipyevents
    - scipy
    - pillow
    - tqdm
    - pytorch =*=cuda*
    - pygltflib

test:
  imports:
    - kaolin

about:
  home: https://developer.nvidia.com/nvidia-kaolin
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: 'A Pytorch Library for Accelerating 3D Deep Learning Research '
  description: |
    NVIDIA Kaolin library provides a PyTorch API for working with a variety
    of 3D representations and includes a growing collection of
    GPU-optimized operations such as modular differentiable rendering,
    fast conversions between representations, data loading,
    3D checkpoints and more.
  dev_url: https://github.com/NVIDIAGameWorks/kaolin
  doc_url: https://kaolin.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - JennaLipscomb
    - mxr-conda
    - h-vetinari
